apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260614-135129-ec1kgp3mfxdm-service
spec:
  selector:
    app: enterprise-system-20260614-135129-ec1kgp3mfxdm
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
